### ISSUE TITLE
Server Crash w/ Rediscovered's Scarecrow

### ISSUE THREAD

**Issue by WenXin20** [Majrusz/MinecraftMods#18] opened 2021-02-02 06:18 UTC
`Minecraft v1.16.5`
`Forge v36.0.7`
[`Rediscovered v1.3.7`](https://www.curseforge.com/minecraft/mc-mods/rediscovered)
`Wonderful Enchantments v1.0.2`

After trying to place the Scarecrow, my server crash. It looks to be related to the vampirism curse.
Related to [Modding-Legacy/Rediscovered#10](https://gitlab.com/modding-legacy/rediscovered/-/issues/10)
[Crash Report](https://gist.github.com/WenXin20/c1e42bbbed70cd312f48cfae421c7472)

**Comment by Majrusz** [comment] 2021-02-05 11:39
Thanks for reporting this. This is caused by my library, not this modification. It will be fixed in the next Majrusz Library update.

**Closed as completed by Majrusz** 2021-02-05 11:39 UTC
Labels: 1.16.X

**Comment by WenXin20** [comment] 2021-02-05 16:24
Ah, thanks!
